### ISSUE TITLE
Accessibility is awesome

### ISSUE THREAD

**Issue by marcysutton** [bayandin/awesome-awesomeness#127]
And it's worthy of being on your list of awesome things. You could even link to the A11yproject: https://github.com/a11yproject/a11yproject.com

**Comment by n1trux** [comment]
I don't think this belongs here. This is a **list of lists** of awesome things, not a list of awesome things ;)

**Comment by marcysutton** [comment]
Well then. I have the perfect thing for you: http://a11ywins.tumblr.com/

**Comment by marcysutton** [comment]
Ahh, I see what you mean. Here is an awesome-a11y repo by @brunopulis: https://github.com/brunopulis/awesome-a11y

**Comment by brunopulis** [comment]
@marcysutton Thanks to remember :smile:

**Comment by n1trux** [comment]
I just [added it to my repo](/n1trux/awesome-awesomeness/commit/6e63799d2adda7c1ae6e4b09b26e0585b3ee1702).

**Comment by brunopulis** [comment]
@n1trux :+1:
