### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [bayandin/awesome-awesomeness#155]
@bayandin thank you for all of your hard work managing this.  I would like to propose a next step for ensuring the longevity and manageability of awesome-everything going forward.

We are creating a github org for all awesome open source repos. I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together. What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org. What are your thoughts? Let me know if there is anything you'd like to discuss!

**Comment by bucaran** [comment]
:+1:

**Comment by jeffreyjackson** [comment]
@bayandin obviously we would make you an owner of this new Organization.  Looking forward to hearing from you and working with you.
