### ISSUE TITLE
Lack of maintainace

### ISSUE THREAD

**Issue by hackerkid** [bayandin/awesome-awesomeness#194]
Even tough this is one of the most starred repos in Github, this repo lacks regular maintenance. Please add a `collaborator` or `merge/close` the open pull requests.

**Comment by arthurvr** [comment]
Or just deprecate in favor of https://github.com/sindresorhus/awesome. Much duplicating now, and that one is really up-to-date and well maintained.

**Comment by m1guelpf** [comment]
@bayandin added contributors and this repo will now be mantained again
