### ISSUE TITLE
Repository is not active

### ISSUE THREAD

**Issue by peterkokot** [bayandin/awesome-awesomeness#208]
I've noticed this is quite popular awesome list but there are a lot of opened pull requests that just sit there unmerged. Is it worth sending pull requests here?

**Comment by sindresorhus** [comment]
https://github.com/bayandin/awesome-awesomeness/issues/194#issuecomment-118435505

**Comment by m1guelpf** [comment]
We are working on this repo rigth now, so @peterkokot yes, it is worth.

**Comment by peterkokot** [comment]
Awesome!
