### ISSUE TITLE
Suggestion: How about put DEPRECATED on README?

### ISSUE THREAD

**Issue by cristianoliveira** [bayandin/awesome-awesomeness#241]
Hi @bayandin and @sindresorhus 

I noticed by #208 and #194 that this repo is not active anymore. How about put it on README and make it clear? Also, we can point out to https://github.com/sindresorhus/awesome.  :)

Cheers

**Comment by Adrion** [comment]
Damn I made a PR 4 days ago. I didn't notice that it was unactive :/ 
+1 for redirection and README update

**Comment by m1guelpf** [comment]
We're working on mantaining the repo, so this isn't necessary.
