### ISSUE TITLE
Repository is abadoned?

### ISSUE THREAD

**Issue by Mehonoshin** [bayandin/awesome-awesomeness#263]
Hi!

Seems that this repo is abadoned.
Does anybody wants to maintain some fork?

**Comment by trash07** [comment]
Hi! I've found a similar list at [Awesome-awesome](https://github.com/emijrp/awesome-awesome). What do you think?

**Comment by Mehonoshin** [comment]
@trash07 it looks that it has less links. This repository contents should be merged there, or someone should maintain current repo.

**Comment by Mehonoshin** [comment]
@bayandin ping

**Comment by assp1r1n3** [comment]
I would like to maintain the repository, but my attempts to reach to the @bayandin failed. I think it is time to make a fork. But the I will have to notify all pending pull requests' creators.

**Comment by bayandin** [comment]
Ok, it seems I need to write something about it.

First of all, I would recommend using other lists of lists of lists of .. well you get it (for example, the most starred by @sindresorhus: https://github.com/sindresorhus/awesome)

But if anyone wants to contribute to this one just left your name below, I'll grant the access.

**Comment by assp1r1n3** [comment]
@bayandin I would like to maintain this repository

**Comment by bayandin** [comment]
@assp1r1n3 Welcome!

**Comment by assp1r1n3** [comment]
@bayandin Thanks!

**Comment by m1guelpf** [comment]
@bayandin I would also like to help

**Comment by bayandin** [comment]
@m1guelpf have fun :)

**Comment by KleoPetroff** [comment]
@bayandin @assp1r1n3 is there a room for one more?

**Comment by bayandin** [comment]
@KleoPetroff yep, go for it!

**Comment by proinsias** [comment]
Can we close this now that we're back on track?

**Comment by m1guelpf** [comment]
@proinsias I think so

**Comment by Chan9390** [comment]
Good work folks.. Cleared many issues on a single day.. Kudos !
