### ISSUE TITLE
awesome-c wrong url

### ISSUE THREAD

**Issue by ty6tu7uytr** [bayandin/awesome-awesomeness#298]
The correct link is https://notabug.org/koz.ross/awesome-c

**Comment by m1guelpf** [comment]
@ty6tu7uytr Could you open a PR?

**Comment by kozross** [comment]
This issue has already been raised by me, and got shot down on the basis of 'Github or GTFO'. On this very repo if memory serves. It *is* true that my list is much better maintained, though.

**Comment by m1guelpf** [comment]
@kozross So the repo with more entries and more mantained is the notabug one?
(Also, I can't find the issue you raised, maybe it was other repository...)

**Comment by ty6tu7uytr** [comment]
> So the repo with more entries and more mantained is the notabug one?

Did you even see the current [awesome-c GitHub link](https://github.com/kozross/awesome-c)? There is not even a single entry in there.

**Comment by KleoPetroff** [comment]
The list was moved to notabug on 28 Feb 2015. (almost two years ago, reference - https://github.com/kozross/awesome-c/commit/30b0d48f3340a7a4b27b28fed1459d6b40cd1e0b).

Let's change the link asap.
