### ISSUE TITLE
Some things are more important than code.

### ISSUE THREAD

**Issue by patrick-gleeson** [bayandin/awesome-awesomeness#458]
Russians are being subjected to a campaign of lies by their own official media, meaning that, while thousands of Russians have died, and continue to die, in the ongoing invasion of Ukraine, their compatriots are neither being told about their deaths nor even what they died for.

Anyone who loves Russia should be concerned about this. The sudden censoring of Twitter and Facebook to prevent the truth from coming out mean Russians must find other ways to inform themselves. Please, learn and spread the truth. Start [here](https://acoup.blog/2022/02/25/miscellanea-understanding-the-war-in-ukraine/), continue [here](https://www.politico.eu/article/ukraine-war-russia-vladimir-putin-miscalculation/). Fight for truth.

**Comment by c80609a** [comment]
Why do you think that "thousands of Russians have died" is true? The all world in grip of Russophobic hysteria.

**Comment by patrick-gleeson** [comment]
> Why do you think that "thousands of Russians have died" is true?

Because outside of Kremlin-controlled sources, that is the conservative consensus of multiple independent fact-checkers. I don't want it to be true. It upset me to hear it. But denial of the truth doesn't change it.

**Comment by c80609a** [comment]
Outside of Kremlin-controlled sources are war gonzos content from the battle field.

![https://ecotrip.me/photo_2022-02-27_13-50-05.jpg](https://ecotrip.me/photo_2022-02-27_13-50-05.jpg)

**Comment by patrick-gleeson** [comment]
Sorry it's taken me so long to reply, I keep trying to, but every time I think about your message I start laughing and can't stop, so I never get round to sending in a response.

Mad king Vladimir has put schoolteachers and caretakers and sent them to die in Ukraine, because none of his people have the spine to stand up to him. The Kremlin is desperate to preserve the lie that it's "liberating" its people, and they're having to shut down all contact with the outside world to prevent the truth from getting in.

This stupid, stupid invasion is only still going because of Russian people who are still in denial of the lunacy of what is happening. And you're still sending pictures of old ladies in helmets?

**Comment by patrick-gleeson** [comment]
Also, _even the Russian Defence Ministry_ is now acknowledging 2000+ Russians have killed and wounded https://www.reuters.com/world/russia-says-498-its-soldiers-killed-1597-wounded-ukraine-ria-2022-03-02/, admitting that the figure they were suggesting yesterday (1!) was a lie. Do you really believe they're telling the whole truth now?

**Comment by c80609a** [comment]
Okay :) https://www.youtube.com/watch?v=MA0sfNKjvEs

**Comment by c80609a** [comment]
Thank god Ukraine nazi is over, plain and simple.

**Comment by patrick-gleeson** [comment]
![WhatsApp Image 2022-02-25 at 5 55 54 PM](https://user-images.githubusercontent.com/12064716/156536331-11865dca-fdb5-4ba5-94d1-084a2211708d.jpeg)

**Comment by patrick-gleeson** [comment]
![download (2)](https://user-images.githubusercontent.com/12064716/156536805-c5cb007e-d4b8-400e-b2f1-63c7878dd9c9.png)

**Comment by patrick-gleeson** [comment]
But yep, Ukraine, the country with the Jewish president whose family were killed in the Holocaust, they're the ones we should compare with the Nazis, not the country that's invading its neighbours in Europe and bombing holocause memorials while their increasingly isolated leader cowers in a bunker....

**Comment by patrick-gleeson** [comment]
I like you! It's a shame you're on the wrong side. When the invasion is over, let's join forces and say mean things about some other countries.

**Comment by c80609a** [comment]
The stock market is not dead. It's just that the state will buy back cheaply the shares of the largest companies, which will return, surprise, to state property.

**Comment by c80609a** [comment]
U're so stupid :)

**Comment by c80609a** [comment]
Continue reading ;)

**Comment by ericblade** [comment]
> Okay, agreed! We're bombing nazi-Ukraine. You continue read the "independent" news. Deal?

This is the dumbest statement I've seen since Trump left office.

Regardless of if you believe thousands of Russians have died -- thousands of Ukrainians have died.  Thousands of *PEOPLE* have died.

No aggressor in this war is doing anything good for anyone.

**Comment by c80609a** [comment]
> > Okay, agreed! We're bombing nazi-Ukraine. You continue read the "independent" news. Deal?
> 
> This is the dumbest statement I've seen since Trump left office.
> 
> Regardless of if you believe thousands of Russians have died -- thousands of Ukrainians have died. Thousands of _PEOPLE_ have died.
> 
> No aggressor in this war is doing anything good for anyone.

the dog may bark but the caravan moves on

**Comment by patrick-gleeson** [comment]
@ericblade what you have to realise is that much like Mandalorians and weapons, trolling is an inherent part of Russian culture. For example, look at any of Sergey Lavrov's public statements. You can't take Russians seriously online, you just have to sit back and enjoy Putin's miserable failures where you can.

And @c80609a, I'd send you some links in return, but your government has banned every website in your country, so you wouldn't be able to read them! You poor little man, imagine being so brainwashed that you believe that the man who's _banning access_ to all information is the one who's telling the truth! At least Marina Ovsyannikova has some backbone, unlike you snivelling little cultists who bury your head in the sand.

**Comment by c80609a** [comment]
https://beyond-coal.eu/russian-fossil-fuel-tracker/

**Comment by SantyagoSeaman** [comment]
> > Okay, agreed! We're bombing nazi-Ukraine. You continue read the "independent" news. Deal?
> 
> This is the dumbest statement I've seen since Trump left office.
> 
> Regardless of if you believe thousands of Russians have died -- thousands of Ukrainians have died. Thousands of _PEOPLE_ have died.
> 
> No aggressor in this war is doing anything good for anyone.

Please, report abuse from the account page of this guy. He is a fascist and must be banned.

**Comment by c80609a** [comment]
> > > Okay, agreed! We're bombing nazi-Ukraine. You continue read the "independent" news. Deal?
> > 
> > 
> > This is the dumbest statement I've seen since Trump left office.
> > Regardless of if you believe thousands of Russians have died -- thousands of Ukrainians have died. Thousands of _PEOPLE_ have died.
> > No aggressor in this war is doing anything good for anyone.
> 
> Please, report abuse from the account page of [c80609a](https://github.com/c80609a). He is a fascist and must be banned.

Dont forget GitLab, Bitbucket, StackOverflow!  :)

**Comment by KleoPetroff** [comment]
This is getting out of hand! While I am, and I believe everyone here as well is, strongly against the war and any activities where innocent people die, this is not the place to discuss this. This is a place to talk about and discuss code and other technical topics, so let's try to keep it that way.
